name: CI Smoke Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  smoketest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma client
        run: npx prisma generate

      - name: Apply Prisma migrations
        run: npx prisma migrate deploy

      - name: Seed DB
        run: npx prisma db seed

      - name: Start backend (background)
        run: |
          nohup npx ts-node src/index.ts > server.log 2>&1 &

      - name: Wait for health
        run: |
          for i in {1..30}; do
            if curl -s http://127.0.0.1:3000/health | grep -q '"status":"ok"'; then
              echo "backend up ✅"
              exit 0
            fi
            sleep 1
          done
          echo "backend failed to start" >&2
          exit 1

      - name: Run smoketest
        run: npm run smoke:local