name: CI Smoke + E2E

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  smoketest:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps (ci)
        run: npm ci

      - name: Generate Prisma client
        run: npx prisma generate

      - name: Apply Prisma migrations (deploy)
        run: npx prisma migrate deploy

      - name: Seed DB
        run: npx prisma db seed

      - name: Ensure test script is executable
        run: chmod +x scripts/smoketest.sh scripts/api-e2e.sh

      - name: Start backend (background)
        run: |
          nohup npm run dev > server.log 2>&1 & echo $! > server.pid
          sleep 1
          echo "pid=$(cat server.pid)"

      - name: Wait for health
        run: |
          for i in {1..60}; do
            if curl -s http://127.0.0.1:3000/health | grep -q '"status":"ok"'; then
              echo "✅ backend up"
              exit 0
            fi
            sleep 1
          done
          echo "❌ backend failed to start"
          exit 1

      - name: Run E2E script
        run: bash scripts/api-e2e.sh

      # ---- Debug & Artefakte (immer ausführen) ----
      - name: Print server.log (last 200 lines)
        if: always()
        run: |
          echo "===== server.log (last 200) ====="
          tail -n 200 server.log || true

      - name: Upload server.log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: server-log
          path: server.log
